Jshimkus rh patch 1
jshimkus-rh/sd-vdo-devel pull request #8
Opened 2023-04-05 17:32 UTC by jshimkus-rh

2023-04-10 21:02 UTC, jshimkus-rh commented on Makefile
>  # SPDX-License-Identifier: GPL-2.0-only
test body

2023-04-11 18:34 UTC, jshimkus-rh commented on Makefile
>  # SPDX-License-Identifier: GPL-2.0-only
test body

2023-04-11 18:43 UTC, jshimkus-rh commented on Makefile
test body

2023-04-11 20:18 UTC, jshimkus-rh commented on Makefile
test body

2023-04-12 13:04 UTC, jshimkus-rh commented on Makefile
test body

2023-04-12 14:11 UTC, jshimkus-rh commented on Makefile
test body

2023-04-12 14:12 UTC, jshimkus-rh commented on Makefile
test body

2023-04-12 14:49 UTC, jshimkus-rh commented on src/tools/README.txt
This is comment at the file level 4/12/23, 10:47

2023-04-12 14:52 UTC, jshimkus-rh commented on src/tools/README.txt
test body

2023-04-12 15:21 UTC, jshimkus-rh commented on src/tools/README.txt
test body

2023-04-12 15:40 UTC, jshimkus-rh commented on src/tools/README.txt
This is comment at the file level 4/12/23, 10:47

2023-04-12 15:43 UTC, jshimkus-rh commented on src/tools/README.txt
This is comment at the file level 4/12/23, 10:47

2023-04-12 15:50 UTC, jshimkus-rh commented on src/tools/README.txt
'This is comment at the file level 4/12/23, 10:47'

2023-04-12 15:52 UTC, jshimkus-rh commented on src/tools/README.txt
This is comment at the file level 4/12/23, 10:47

2023-04-12 15:56 UTC, jshimkus-rh commented on src/tools/README.txt
'This is comment at the file level 4/12/23, 10:47'

2023-04-12 16:09 UTC, jshimkus-rh commented on src/tools/README.txt
'This is comment at the file level 4/12/23, 10:47'

2023-04-12 16:15 UTC, jshimkus-rh commented on src/tools/README.txt
'This is comment at the file level 4/12/23, 10:47'

2023-04-12 16:42 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
Line 1 comment

2023-04-12 16:45 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
Line 1 comment

2023-04-12 16:50 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
What the what?

2023-04-12 18:10 UTC, jshimkus-rh commented on src/tools/README.txt
'April 12, 2023 at 14:09:47 EDT'

2023-04-12 18:10 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
'line 45'

2023-04-12 18:10 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
'line 44 to 45'

2023-04-12 18:32 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
foo

2023-04-12 18:35 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
doo

2023-04-12 18:51 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
edlkjadeflkj

2023-04-12 19:56 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
ff

2023-04-12 20:13 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
fopp

2023-04-12 20:26 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
tewt

2023-04-12 20:37 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
foo

2023-04-12 20:38 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
foo

2023-04-12 20:41 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
foo

2023-04-12 20:44 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
foo

2023-04-12 20:46 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
fpop

2023-04-12 20:49 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
foo

2023-04-12 20:57 UTC, jshimkus-rh commented on src/tools/README.txt
> +
foo

2023-04-12 21:10 UTC, jshimkus-rh commented on src/tools/README.txt
> +
f

2023-04-12 21:22 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
foo

2023-04-12 21:22 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
foo

2023-04-12 21:22 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
foo

2023-04-13 14:19 UTC, jshimkus-rh commented on src/tools/README.txt
> +
fpp

2023-04-13 14:22 UTC, jshimkus-rh commented on src/tools/README.txt
> +
f

2023-04-13 14:24 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
this is lines fourty-four and forty-five.

2023-04-13 15:29 UTC, jshimkus-rh commented on Makefile
This is a post-change file comment.

2023-04-13 15:29 UTC, jshimkus-rh commented on Makefile
> -# Copyright Red Hat
should keep 'Red Hat'

2023-04-13 15:29 UTC, jshimkus-rh commented on Makefile
> +# Copyright The Great Bird of The Galaxy
should not have changed

2023-04-13 15:29 UTC, jshimkus-rh commented on src/tools/README.txt
This is a post-change README comment.

2023-04-13 15:29 UTC, jshimkus-rh commented on src/tools/README.txt
This is a pre-change README comment.

2023-04-13 15:29 UTC, jshimkus-rh commented on src/tools/README.txt
> +
this is a blank line

2023-04-13 15:29 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
this is a fantastic change

2023-04-13 17:58 UTC, jshimkus-rh commented
what the what

2023-04-13 19:57 UTC, jshimkus-rh commented
pr comment

2023-04-13 19:57 UTC, jshimkus-rh commented on Makefile
new Makefile file comment

2023-04-13 19:57 UTC, jshimkus-rh commented on Makefile
old Makefile file comment

2023-04-13 19:57 UTC, jshimkus-rh commented on Makefile
> +# Copyright The Great Bird of The Galaxy
new line one comment

2023-04-13 19:57 UTC, jshimkus-rh commented on Makefile
> -# Copyright Red Hat
old line one comment

2023-04-13 19:57 UTC, jshimkus-rh commented on src/tools/README.txt
new README comment

2023-04-13 19:57 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
multi-line

2023-04-13 21:29 UTC, jshimkus-rh commented on src/tools/README.txt
comment from generalized REST api.

2023-04-13 21:29 UTC, jshimkus-rh commented on src/tools/README.txt
> +
line

2023-04-13 21:31 UTC, jshimkus-rh commented on src/tools/README.txt
This day is call'd the feast of Crispian. He that outlives this day, and comes safe home, Will stand a tip-toe when this day is nam'd, And rouse him at the name of Crispian. He that shall live this day, and see old age, Will yearly on the vigil feast his neighbours, And say 'To-morrow is Saint Crispian.' Then will he strip his sleeve and show his scars, And say 'These wounds I had on Crispian's day.' Old men forget; yet all shall be forgot, But he'll remember, with advantages, What feats he did that day. Then shall our names, Familiar in his mouth as household words- Harry the King, Bedford and Exeter, Warwick and Talbot, Salisbury and Gloucester- Be in their flowing cups freshly rememb'red. This story shall the good man teach his son; And Crispin Crispian shall ne'er go by, From this day to the ending of the world, But we in it shall be remembered- We few, we happy few, we band of brothers; For he to-day that sheds his blood with me Shall be my brother; be he ne'er so vile, This day shall gentle his condition; And gentlemen in England now-a-bed Shall think themselves accurs'd they were not here, And hold their manhoods cheap whiles any speaks That fought with us upon Saint Crispin's day.

2023-04-13 21:39 UTC, jshimkus-rh commented
fileCommentInfo

2023-04-13 21:55 UTC, jshimkus-rh commented on Makefile
print("Processing comments", end = "")

2023-04-13 21:55 UTC, jshimkus-rh commented on src/tools/README.txt
print("Processing comments", end = "")

2023-04-13 21:59 UTC, jshimkus-rh commented
print("Processing comments", end = "")

2023-04-13 21:59 UTC, jshimkus-rh commented on Makefile
print("Processing comments", end = "")

2023-04-13 21:59 UTC, jshimkus-rh commented on src/tools/README.txt
print("Processing comments", end = "")

2023-04-14 20:37 UTC, jshimkus-rh commented on Makefile
comment

2023-04-14 20:37 UTC, jshimkus-rh commented on Makefile
> +# Copyright The Great Bird of The Galaxy
copy

2023-04-14 20:38 UTC, jshimkus-rh commented on src/tools/README.txt
comment

2023-04-14 22:50 UTC, jshimkus-rh commented
Overall commment April 14, 2023 at 18:40:09 EDT

2023-04-14 22:50 UTC, jshimkus-rh commented on Makefile
File comment April 14, 2023 at 18:40:29 EDT

2023-04-14 22:50 UTC, jshimkus-rh commented on Makefile
> -# Copyright Red Hat
left line comment

2023-04-14 22:50 UTC, jshimkus-rh commented on Makefile
> +# Copyright The Great Bird of The Galaxy
right line comment

2023-04-14 22:50 UTC, jshimkus-rh commented on src/tools/README.txt
File comment April 14, 2023 at 18:41:35 EDT

2023-04-14 22:50 UTC, jshimkus-rh commented on src/tools/README.txt
> +
single-line comment

2023-04-14 22:50 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
multi-line comment

2023-04-17 13:45 UTC, jshimkus-rh commented
general comment

2023-04-17 13:45 UTC, jshimkus-rh commented on src/tools/README.txt
readme

2023-04-17 13:46 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
new

2023-04-18 18:32 UTC, jshimkus-rh commented
commn

2023-04-19 13:32 UTC, jshimkus-rh commented on src/tools/README.txt
file

2023-04-19 13:41 UTC, jshimkus-rh commented
pull

2023-04-19 13:42 UTC, jshimkus-rh commented on src/tools/README.txt
file

2023-04-19 13:42 UTC, jshimkus-rh commented on src/tools/README.txt
> +
a44

2023-04-19 13:42 UTC, jshimkus-rh commented
pull

2023-04-19 13:42 UTC, jshimkus-rh commented on src/tools/README.txt
file

2023-04-19 13:42 UTC, jshimkus-rh commented on src/tools/README.txt
> +
a44

2023-04-19 13:43 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
45

2023-04-21 13:54 UTC, jshimkus-rh commented
PULL LEVEL - April 21, 2023 at 09:53:48 EDT

2023-04-21 13:54 UTC, jshimkus-rh commented on Makefile
PULL LEVEL - April 21, 2023 at 09:53:48 EDT

2023-04-21 13:54 UTC, jshimkus-rh commented on Makefile
> +# Copyright The Great Bird of The Galaxy
PULL LEVEL - April 21, 2023 at 09:53:48 EDT

2023-04-21 14:20 UTC, jshimkus-rh commented
pull comment

2023-04-21 14:50 UTC, jshimkus-rh commented
Probably shows up as jshimkus-rh

2023-04-21 14:56 UTC, jshimkus commented on Makefile
How 'bout this?

2023-04-21 14:56 UTC, jshimkus commented on Makefile
> +# Copyright The Great Bird of The Galaxy
and this?

2023-04-21 15:03 UTC, jshimkus requested changes
Previous didn't seem to take.

2023-04-21 15:05 UTC, jshimkus commented on Makefile
>  # SPDX-License-Identifier: GPL-2.0-only
Review comment on line?  There was only one so maybe/maybe not.

2023-04-21 15:08 UTC, jshimkus-rh commented on Makefile
> +# Copyright The Great Bird of The Galaxy
'line 3 from jshimkus'

2023-04-21 15:10 UTC, jshimkus commented
globqal

2023-04-21 15:28 UTC, jshimkus-rh reviewed
This is the review body.

2023-04-21 15:42 UTC, jshimkus reviewed
This should be from jshimkus (using that token).

2023-04-21 15:45 UTC, jshimkus reviewed
?

2023-04-21 15:46 UTC, jshimkus-rh commented
fff

2023-04-21 15:47 UTC, jshimkus-rh commented on src/tools/README.txt
> +
dddd

2023-04-21 15:48 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
argh!!!!

2023-04-21 15:51 UTC, jshimkus commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
single comment

2023-04-21 16:06 UTC, jshimkus reviewed
finishing aaa

2023-04-21 16:06 UTC, jshimkus commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
aaa

2023-04-21 16:07 UTC, jshimkus-rh commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
foo

2023-04-21 16:08 UTC, jshimkus reviewed
starting a review to comment

2023-04-21 16:09 UTC, jshimkus reviewed
finihing

2023-04-21 16:09 UTC, jshimkus commented on src/tools/README.txt
> +jbs: some additional text just to create a PR.
ffff

2023-04-21 16:10 UTC, jshimkus-rh commented
General comment

2023-04-21 16:12 UTC, jshimkus-rh commented on Makefile
> +# Copyright The Great Bird of The Galaxy
lien 3

2023-04-21 16:13 UTC, jshimkus-rh commented
general

2023-04-21 20:09 UTC, jshimkus-rh commented on Makefile
file

2023-04-21 20:11 UTC, jshimkus reviewed
the review

2023-04-21 20:11 UTC, jshimkus commented on Makefile
> +# Copyright The Great Bird of The Galaxy
a line

2023-04-21 20:13 UTC, jshimkus reviewed
done

2023-04-21 20:13 UTC, jshimkus commented on Makefile
> -# Copyright Red Hat
left

2023-04-21 20:13 UTC, jshimkus commented on Makefile
> +# Copyright The Great Bird of The Galaxy
right

2023-04-21 20:14 UTC, jshimkus-rh commented
general

2023-04-21 20:14 UTC, jshimkus-rh commented on Makefile
makefile

2023-04-21 20:14 UTC, jshimkus-rh commented on Makefile
> +# Copyright The Great Bird of The Galaxy
line

2023-04-24 12:52 UTC, closed without merging

2023-04-24 21:33 UTC, jshimkus-rh commented on Makefile
file

2023-04-24 21:33 UTC, jshimkus-rh commented on Makefile
> +# Copyright The Great Bird of The Galaxy
line